# Generated by Django 6.0.1 on 2026-02-04 21:14

import educational_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('userid', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=educational_products.models.upload_image)),
                ('actived', models.BooleanField(default=False)),
                ('Entered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
