# Generated by Django 6.0.1 on 2026-02-05 20:03

import django.db.models.deletion
import educational_products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Entered_date',
            field=models.DateTimeField(verbose_name='سال ورود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='actived',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=educational_products.models.upload_image, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی دانشجو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دانشجو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='userid',
            field=models.IntegerField(verbose_name='شماره دانشجویی'),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('professor', models.CharField(max_length=100, verbose_name='استاد')),
                ('exam_date', models.DateField(verbose_name='تاریخ امتحان')),
                ('exam_time', models.TimeField(verbose_name='ساعت امتحان')),
                ('location', models.CharField(max_length=100, verbose_name='مکان')),
                ('seat_number', models.CharField(max_length=20, verbose_name='شماره صندلی')),
                ('status', models.CharField(default='تأیید شده', max_length=50, verbose_name='وضعیت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'برنامه امتحانی',
                'verbose_name_plural': 'برنامه\u200cهای امتحانی',
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
        migrations.CreateModel(
            name='GraduationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('student_id', models.CharField(max_length=20, verbose_name='شماره دانشجویی')),
                ('major', models.CharField(choices=[('computer_science', 'مهندسی کامپیوتر'), ('software_engineering', 'مهندسی نرم\u200cافزار'), ('it', 'فناوری اطلاعات'), ('ce', 'مهندسی عمران'), ('ee', 'مهندسی برق')], max_length=50, verbose_name='رشته تحصیلی')),
                ('degree', models.CharField(choices=[('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='مقطع تحصیلی')),
                ('graduation_semester', models.CharField(max_length=50, verbose_name='نیمسال فارغ\u200cالتحصیلی')),
                ('graduation_date', models.DateField(verbose_name='تاریخ پیشنهادی فارغ\u200cالتحصیلی')),
                ('thesis_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان پایان\u200cنامه/پروژه')),
                ('supervisor_name', models.CharField(blank=True, max_length=100, verbose_name='نام استاد راهنما')),
                ('remarks', models.TextField(blank=True, verbose_name='توضیحات/ملاحظات')),
                ('agree_to_terms', models.BooleanField(default=False, verbose_name='موافقت با قوانین')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('need_correction', 'نیاز به اصلاح')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست فارغ\u200cالتحصیلی',
                'verbose_name_plural': 'درخواست\u200cهای فارغ\u200cالتحصیلی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='شماره دانشجویی')),
                ('major', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('entry_year', models.IntegerField(verbose_name='سال ورود')),
                ('gpa', models.FloatField(default=0.0, verbose_name='معدل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل دانشجو',
                'verbose_name_plural': 'پروفایل\u200cهای دانشجویی',
            },
        ),
    ]
