# Generated by Django 6.0.1 on 2026-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_products', '0002_alter_product_entered_date_alter_product_actived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationrequest',
            name='graduation_semester',
            field=models.CharField(choices=[('fall_1404', 'پاییز ۱۴۰۴'), ('spring_1405', 'بهار ۱۴۰۵'), ('summer_1405', 'تابستان ۱۴۰۵')], max_length=50, verbose_name='نیمسال فارغ\u200cالتحصیلی'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
