# Generated by Django 6.0.1 on 2026-02-07 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_products', '0003_alter_graduationrequest_graduation_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='شماره دانشجویی')),
                ('major', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('entry_year', models.IntegerField(verbose_name='سال ورود')),
                ('gpa', models.FloatField(default=0.0, verbose_name='معدل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل دانشجو',
                'verbose_name_plural': 'پروفایل\u200cهای دانشجویی',
            },
        ),
    ]
