# Generated by Django 6.0.1 on 2026-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_products', '0004_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='exam_date',
            field=models.CharField(verbose_name='تاریخ امتحان'),
        ),
    ]
