# Generated by Django 6.0.1 on 2026-02-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_products', '0005_alter_examschedule_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='exam_date',
            field=models.CharField(max_length=20, verbose_name='تاریخ امتحان'),
        ),
    ]
