# Generated by Django 6.0.1 on 2026-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_products', '0006_alter_examschedule_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guide_professor',
            field=models.CharField(default='non', max_length=100, verbose_name='استاد راهنما'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='units',
            field=models.IntegerField(default=0, verbose_name='واحد های گذرانده'),
            preserve_default=False,
        ),
    ]
